M48
; DRILL file {KiCad 6.0.9} date Fri 09 Dec 2022 21:33:21 CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-12-09T21:33:21+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0689
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1570
%
G90
G05
T1
X4.105Y-2.5656
X4.3325Y-2.5656
T2
X3.2687Y-3.5
X3.6687Y-3.5
X4.0187Y-3.5
X4.4188Y-3.5
X4.7687Y-3.5
X5.1688Y-3.5
T3
X3.4688Y-3.5
X4.2188Y-3.5
X4.9688Y-3.5
T0
M30
